color: null
description: null
fieldLayouts:
  cb77e89a-f9e5-4256-b7b1-f97c107cccb5:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-12-08T15:40:32+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 1f814a42-5fc2-4020-a6cb-63ce955df968
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-12-15T17:17:37+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: a9c5c515-d858-4a56-9491-4b0e57376c36 # Description
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 86eef275-762b-4c33-b963-151cbbb6d508
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-12-14T12:18:08+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 7968bafd-fd4d-4fc1-9a33-5116e62eab1d # Modules
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: aa284de5-42a5-4ad2-b6ca-051997d0c513
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: bcdf55f2-ba04-4ae1-ae15-74be6ef13692
        userCondition: null
handle: homepageEntry
hasTitleField: true
icon: null
name: 'Home Page'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
