columnSuffix: null
handle: streamingPlatformsDropdown
instructions: null
name: 'Streaming Platforms Dropdown'
searchable: false
settings:
  customOptions: false
  options:
    -
      __assoc__:
        -
          - label
          - ''
        -
          - value
          - ''
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - YouTube
        -
          - value
          - youtube
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Spotify
        -
          - value
          - spotify
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Bandcamp
        -
          - value
          - bandcamp
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - AppleMusic
        -
          - value
          - applemusic
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
