fieldLayouts:
  06cd7103-eb4c-4fea-906e-9f509c1f43dd:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-12-14T13:07:44+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 55e080a1-4fb8-4404-9c1b-7694524ff1ee # Title
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 96ec6c61-5aab-4887-b378-354d3e842d9b
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-12-14T13:07:44+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: a9c5c515-d858-4a56-9491-4b0e57376c36 # Description
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a2dc9702-a84e-4bed-805e-7bba30c23821
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-12-14T14:27:20+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 2c9366bb-4de0-4c43-a8bf-50e3116e21b2 # Button Text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b702488b-9540-4fe6-a029-b83a27411af0
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-12-14T13:07:44+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: e6ecced8-cbaf-4fb3-8a6f-ebff85a76a62 # Image Collection
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2b140022-09a8-4577-bfe1-365e08a1a800
            userCondition: null
            warning: null
            width: 100
        name: 'Promo Section'
        uid: 5f04517e-d341-4ee1-8f9e-a1c6bec5dfc1
        userCondition: null
handle: promoSection
name: 'Promo section'
sortOrder: 7
