defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 8b3119a0-2fb5-4ba7-8068-4d0057eaf8c3 # About Page
handle: aboutPage
maxAuthors: 1
name: About
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  72554fa0-3d5f-4a97-b983-ef76386e4536: # English
    enabledByDefault: true
    hasUrls: true
    template: about/_entry.twig
    uriFormat: about
type: single
