defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 1ea72fcf-20f2-49d3-86a8-44cd7426254a # Album Details
handle: albums
maxAuthors: 1
name: Albums
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  72554fa0-3d5f-4a97-b983-ef76386e4536: # English
    enabledByDefault: true
    hasUrls: true
    template: pages/albums/_entry.twig
    uriFormat: 'albums/{slug}'
type: channel
