defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 69007a91-49c9-4bb3-8bab-2baea7e9b260 # Artist Profile
handle: artists
maxAuthors: 1
name: Artists
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  72554fa0-3d5f-4a97-b983-ef76386e4536: # English
    enabledByDefault: true
    hasUrls: true
    template: pages/artists/_entry.twig
    uriFormat: 'artists/{slug}'
  e2b0b11f-ec9d-4b6c-8a49-3c2432648e8d: # Srpskohrvatski
    enabledByDefault: true
    hasUrls: true
    template: pages/artists/_entry.twig
    uriFormat: 'bendovi/{slug}'
type: channel
