defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 3bd68375-ba91-4142-9f8a-9c2ad1d56e8c # Event Details
handle: events
maxAuthors: 1
name: Events
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  72554fa0-3d5f-4a97-b983-ef76386e4536: # English
    enabledByDefault: true
    hasUrls: true
    template: events/_entry.twig
    uriFormat: 'events/{slug}'
type: channel
