defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 6b69b2a1-7434-4d7c-ab13-a468706f0759 # Generic Page
handle: genericPages
maxAuthors: 1
name: 'Generic Pages'
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  72554fa0-3d5f-4a97-b983-ef76386e4536: # English
    enabledByDefault: true
    hasUrls: true
    template: pages/generic/_entry.twig
    uriFormat: "{parent.uri ? parent.uri ~ '/' : ''}{slug}"
  e2b0b11f-ec9d-4b6c-8a49-3c2432648e8d: # Srpskohrvatski
    enabledByDefault: true
    hasUrls: true
    template: pages/generic/_entry.twig
    uriFormat: "{parent.uri ? parent.uri ~ '/' : ''}{slug}"
structure:
  maxLevels: null
  uid: a995a780-7952-44b4-9482-68029c427d8b
type: structure
