defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 7c5f1b78-d42d-4400-b496-33609246dd83 # Home Page
handle: homepage
maxAuthors: 1
name: Homepage
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  72554fa0-3d5f-4a97-b983-ef76386e4536: # English
    enabledByDefault: true
    hasUrls: true
    template: index.twig
    uriFormat: homepage
type: single
