defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 22053b2d-7f52-4a35-a034-0def65641e93 # News Article
handle: news
maxAuthors: 1
name: News
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  72554fa0-3d5f-4a97-b983-ef76386e4536: # English
    enabledByDefault: true
    hasUrls: true
    template: news/_entry.twig
    uriFormat: 'news/{slug}'
type: channel
