defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 25b6d25e-4bac-475f-889f-6e83d371ba75 # Song Details
handle: songs
maxAuthors: 1
name: Songs
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  72554fa0-3d5f-4a97-b983-ef76386e4536: # English
    enabledByDefault: true
    hasUrls: true
    template: songs/_entry.twig
    uriFormat: 'songs/{slug}'
type: channel
